version: "1.0"
info:
  model: int-scaffold
packages:
- name: KMAT_AZSPRO_Jun25Project
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm/KMAT_AZSPRO_Jun25Project
  gitUsername: karthikbm
  gitBranch: main
- name: ApiClient
  version: "1.0"
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
services:
- serviceName: project.kmat_azspro_jun25.integrations:addints
  packages:
  - name: KMAT_AZSPRO_Jun25Project
    version: "1.0"
  - name: ApiClient
    version: "1.0"
  - name: OriginKMAT_Jun2024
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.29
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.989
