version: "1.0"
info:
  model: int-scaffold
packages:
- name: KMAT_AZSPRO_Jun25Project
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm/KMAT_AZSPRO_Jun25Project
  gitUsername: karthikbm
  gitBranch: main
